[package]
name = "pica-convert"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.45", features = ["derive"] }
image = "0.25.6"
serde = { version = "1.0.219", features = ["derive"] }
serde-xml-rs = "0.8.1"

[build-dependencies]
cc = "1.2.34"
